In [16]:
import tensorflow as tf

In [17]:
a1 = tf.constant([
    [[1,1],[1,1],[1,1]],
    [[1,1],[1,1],[1,1]],
    [[1,1],[1,1],[1,1]],
    [[1,1],[1,1],[1,1]]
])

a2 = tf.constant([
    [[1,1],[1,1]],
    [[1,1],[1,1]],
    [[1,1],[1,1]],
    [[1,1],[1,1]]
])

In [18]:
sess = tf.Session()
sess.run(tf.shape(a1))

array([4, 3, 2], dtype=int32)

In [19]:
sess.run(tf.shape(a2))

array([4, 2, 2], dtype=int32)

In [20]:
a1 = tf.transpose(a1,[2,1,0])
print(sess.run(tf.shape(a1)))
print(sess.run(a1))

a1 = tf.batch_to_space_nd(a1, [2], [[0,0]])
print(sess.run(tf.shape(a1)))
print(sess.run(a1))

a1 = tf.transpose(a1,[2,1,0])
print(sess.run(tf.shape(a1)))
print(sess.run(a1))

[2 3 4]
[[[1 1 1 1]
  [1 1 1 1]
  [1 1 1 1]]

 [[1 1 1 1]
  [1 1 1 1]
  [1 1 1 1]]]
[1 6 4]
[[[1 1 1 1]
  [1 1 1 1]
  [1 1 1 1]
  [1 1 1 1]
  [1 1 1 1]
  [1 1 1 1]]]
[4 6 1]
[[[1]
  [1]
  [1]
  [1]
  [1]
  [1]]

 [[1]
  [1]
  [1]
  [1]
  [1]
  [1]]

 [[1]
  [1]
  [1]
  [1]
  [1]
  [1]]

 [[1]
  [1]
  [1]
  [1]
  [1]
  [1]]]
